import type { GameMessage } from "./types";

export const initialMessage: GameMessage = {
  id: "initial-dm-message",
  sender: "DM",
  content: `<h3>¡Bienvenidos a "El Dragón del Pico Agujahelada"!</h3><p>Acabáis de llegar al pueblo de <strong>Phandalin</strong> tras varios días de viaje por caminos escarpados. El aire gélido de las Montañas de la Espada os recibe en este asentamiento minero que lucha por resurgir de sus cenizas. Casas de madera nueva se mezclan con ruinas de piedra, testigos de una grandeza pasada. Sin embargo, una sombra se cierne sobre el pueblo: un joven dragón blanco llamado <strong>Cryovain</strong> ha reclamado el cercano Pico Agujahelada, y su presencia empuja a orcos y otras bestias a las tierras bajas.</p><p>Os encontráis en la plaza del pueblo. A vuestro alrededor, la vida continúa con una tensión palpable. Podéis ver la modesta <strong>Posada Rocacolina</strong>, la tienda de <strong>Suministros Barthen</strong>, el <strong>Bazar Escudo de León</strong>, un pequeño <strong>Santuario de la Suerte</strong>, la <strong>Casa de Cambio</strong> y la residencia del alcalde <strong>Harbin Wester</strong>. Justo enfrente, junto a la casa consistorial, un <strong>tablón de anuncios</strong> de madera atrae vuestra atención con varios carteles escritos con caligrafía nerviosa.</p><p>El futuro de Phandalin es incierto. Sus gentes necesitan héroes. ¿Qué hacéis?</p>`,
  originalContent: `¡Bienvenidos a "El Dragón del Pico Agujahelada"! Acabáis de llegar al pueblo de Phandalin tras varios días de viaje por caminos escarpados. El aire gélido de las Montañas de la Espada os recibe en este asentamiento minero que lucha por resurgir de sus cenizas. Casas de madera nueva se mezclan con ruinas de piedra, testigos de una grandeza pasada. Sin embargo, una sombra se cierne sobre el pueblo: un joven dragón blanco llamado Cryovain ha reclamado el cercano Pico Agujahelada, y su presencia empuja a orcos y otras bestias a las tierras bajas. Os encontráis en la plaza del pueblo. A vuestro alrededor, la vida continúa con una tensión palpable. Podéis ver la modesta Posada Rocacolina, la tienda de Suministros Barthen, el Bazar Escudo de León, un pequeño Santuario de la Suerte, la Casa de Cambio y la residencia del alcalde Harbin Wester. Justo enfrente, junto a la casa consistorial, un tablón de anuncios de madera atrae vuestra atención con varios carteles escritos con caligrafía nerviosa. El futuro de Phandalin es incierto. Sus gentes necesitan héroes. ¿Qué hacéis?`,
  timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
};

